apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    #targetPort: 30065
  selector:
    app: service-go
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: service-go
  template:
    metadata:
      labels:
        app: service-go
      {{- if .Values.metrics }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
      {{- end}}
    spec:
      containers:
      - image: souzapro/simple-service-citiesworld:{{ .Values.version}}
        name: service-go
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http